---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: hardeep8011/junit-devops
        source: pull
    - name: Run container
      shell: docker run -it -d hardeep8011/junit-devops